name: Build M1 Wheels

on:
  push:

jobs:
  build_wheels:
    name: Build wheel on Mac M1
    runs-on: [macos-latest]
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set up environment
        run: |
          arch -arm64 $CONDA/bin/conda install -c conda-forge gfortran
          which gfortran
          gfortran --version

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.3.1
        env:
          CIBW_ARCHS_MACOS: arm64
          CIBW_SKIP: pp*
          CIBW_REPAIR_WHEEL_COMMAND_MACOS: ""

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: wheelhouse/*.whl
